### ISSUE TITLE
Update Table interface

### ISSUE THREAD

**Issue by georgiana-b** [frictionlessdata/tableschema-rb#20]
The functionality of `Table` class should be brought up-to-date with [the proposed interface](https://github.com/frictionlessdata/implementations#tableschema) and v1 spec changes:

- [x] add  `missingValues` property that defines what values should be considered null
- [x] add `headers` property
- [ ] check that existing `primaryKeys` and `foreignKeys` functionality is in accordance with v1 specs 
- [ ] save to filesystem ?

**Comment by roll** [comment]
@georgiana-b 
I moved `missingValues` to #24 because this two has different priorities.
