### ISSUE TITLE
Rename library "tableschema"

### ISSUE THREAD

**Issue by georgiana-b** [frictionlessdata/tableschema-rb#22]
Although the project name has been changed, the gem (library) is still named `jsontableschema`. Rename it to `tableschema`.

**Comment by georgiana-b** [comment]
*Note: gem in Ruby = package  in Python*
According to [this RubyGems thread](http://help.rubygems.org/discussions/questions/104-how-should-i-handle-the-rename-of-a-gem) there is no mechanism to support a gem rename. The common practice is to publish a new gem with the new name and tell our users to switch to the new gem.
This [stackoverflow answer](https://stackoverflow.com/questions/13440438/how-to-rename-a-gem) offers a nice summary of steps to take in order to make a smooth transition. So, based on that answer I propose the following strategy:

1. Make a fork of this repository called `frictionlessdata/jsontableschema-rb` that will keep this code 
and any other pre-Version 1 features
2. Change location of [`jsontableschema` gem](https://rubygems.org/gems/jsontableschema) to  the new fork `frictionlessdata/jsontableschema-rb`
2. On `frictionlessdata/jsontableschema-rb` repo:
- [ ] add deprication warning as post install task
- [ ] make a new release that contains the deprication
- [ ] let people know in repo description and README that the gem is replaced by 
`frictionlessdata/tableschema-rb`
- [ ] let people know the gem will no longer be maintaned 
3. On `frictionlessdata/tableschema-rb` repo (this):
- [ ] rename files, classes and update gemspec
- [ ] publish the renamed code in a new gem called `tableschema`
- [ ] integrate with rubygems 
- [ ] push all Version 1 features here

If we really want to rename the gem I think this is a good time because it's right before Version 1 and the gem still has [few users according to GitHub](https://github.com/search?l=Ruby&q=%27jsontableschema%27+-user%3Africtionlessdata&type=Code&utf8=%E2%9C%93).

@roll WDYT about :point_up: ? Also, I noticed that https://github.com/frictionlessdata/jsontableschema-rb redirects here (among other names :smile:). Any idea if we can change that?

**Comment by roll** [comment]
@georgiana-b 
I think we just could start publish as `tableschema` starting from `0.3.0`. It's pretty non breaking change because old users will be using `jsontableschema` gem. And if they will visit https://github.com/frictionlessdata/jsontableschema-rb, they get readme with new name to rebase on `tableschema`. Also because of renaming there is no further pressure with `do not break things` stuff so you're in a good position.

So I see it's much simpler - just grep/replace all jsontableschema to tableschema. And we release it as `tableschema@0.3` gem. I've done so for Python and JavaScript without any user complains.

**Comment by roll** [comment]
And you could add in readme link to https://github.com/frictionlessdata/tableschema-rb/releases/tag/v0.2.1 (as the last `jsontableschema` release). So we don't need to keep to repos.

**Comment by georgiana-b** [comment]
@roll Sounds good. I'll also add a 0.2.2. containing a post install deprication warning for `jsontableschema` just to be nice.
