### ISSUE TITLE
Update jsonschemas to specs-v1

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-rb#25]
# Overview

Across libraries I use simple approach to sync with specs - https://github.com/frictionlessdata/tableschema-py/blob/master/Makefile#L16-L17. So you could:

- add something like this (also you could add test to check jsonschema is not out-of-date)
- then update jsonschema
- and fix all stuff which is not compatible with Table Schema v1

---

@georgiana-b 
I'm creating it as a separate issue because that's an important step and it leads to changes across the whole library. Small fixes in all classes, tests etc

**Comment by roll** [comment]
That's current Table Schema jsonschema - https://specs.frictionlessdata.io/schemas/table-schema.json

**Comment by roll** [comment]
@georgiana-b 
Related to dir with jsonschemas. The latest state of Python/JavaScript libs is to have jsonschemas in `src/profiles/` dir - https://github.com/frictionlessdata/datapackage-js/tree/master/src (For ruby it could be `lib/profiles/`). Not really important but just a note.

Name selection is based on the fact that `schemas` is really confusing because there is Table Schema and JSON Schema terms.

**Comment by roll** [comment]
So we validate `descriptors` against `profiles` (which is technically JSON Schema docs/dicts)

**Comment by georgiana-b** [comment]
@roll The link to the current Table Schema jsontableschema https://specs.frictionlessdata.io/schemas/table-schema.json doesn't point to that JSON anymore.

Is this intentional? Is there a more reliable reference to the latest TableSchema jsontableschema?

**Comment by roll** [comment]
@georgiana-b 
Closing as working now
